#!/usr/bin/env bash
# Only displays the username, user id, and user home directory path 
#   for the content of /etc/passwd file.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
