#!/usr/bin/env bash
#displays Best School 10 times, 
#but for the 9th iteration, displays Best School 
#and then Hi on a new line

y=0
z="Best School"
while [ $y -lt 10 ]
do
    echo "$z"
    (( y++ ))
    if [ $y -eq 9 ]
    then
	echo "Hi"
     fi
done
