#!/usr/bin/env bash
# fix a container to run Nginx as nginx user listening on 8080  
sed -i -e "s/#user www-data/user nginx/" -e "s/80/8080/g" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
